<?php
namespace app\backend\controller;
use think\Controller;
use think\Session;
use think\Db;

use  think\Request;

class Base extends Controller
{
    public $id;
    //防住直接进入页面
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $type = Session::get('type');
        if(!in_array($type,[1,2])){
             $this->redirect('/backend/login/login');
        }
        if(!Db::name('admin')->where('admin_id', Session::get('user')['admin_id'])->count()){
            $this->error('请重新登录', url('backend/login/login'));
        }
    }
    //图片上传
    public function upload_img(){
        $file = request()->file('file'); // 获取上传的文件
        if($file==null){
            exit(json_encode(array('code'=>1,'msg'=>'未上传图片')));
        }
        // 获取文件后缀
        $temp = explode(".", $_FILES["file"]["name"]);
        $extension = end($temp);
        // 判断文件是否合法
        if(!in_array($extension,array("gif","jpeg","jpg","png"))){
            exit(json_encode(array('code'=>1,'msg'=>'上传图片不合法')));
        }
        $info = $file->move(ROOT_PATH.'public'.DS.'uploads'); // 移动文件到指定目录 没有则创建
        $img = '/uploads/'.$info->getSaveName();
        $imgs =str_replace('\\',"/",$img);
        exit(json_encode(array('code'=>0,'msg'=>$imgs)));
    }
    //富文本上传图片
    public function lay_img_upload()
    {
        $file = Request::instance()->file('file');
        if(empty($file)){
            $result["code"] = "1";
            $result["msg"] = "请选择图片";
            $result['data']["src"] = '';
        }else{
            // 移动到框架应用根目录/public/uploads/ 目录下
            $info = $file->move(ROOT_PATH . 'public' . DS . 'uploads/layui' );
            if($info){
                $name_path =str_replace('\\',"/",$info->getSaveName());
                //成功上传后 获取上传信息
                $result["code"] = '0';
                $result["msg"] = "上传成功";
                $result['data']["src"] = "/uploads/layui/".$name_path;
            }else{
                // 上传失败获取错误信息
                $result["code"] = "2";
                $result["msg"] = "上传出错";
                $result['data']["src"] ='';
            }
        }
        return json_encode($result);
    }
    //退出登录，清除session
    public function loginOut()
    {
        Session::clear();
        $this->redirect('backend/login/login');
    }

}